@if not "%1"=="debug" @echo off
setlocal EnableDelayedExpansion
set tbp-core=%~dp0
call :display-menu
echo.
set /p choice=Choice:
call :menu %choice%
goto :eof

:display-menu
echo 1. Create Project
echo 2. Compile Project
goto :eof

:menu
cls
if %1==1 (
echo Create Where? - To paste, just right click.
echo [e.g. %USERPROFILE%\Documents\TumbleBatchProjects\Project1]
set /p loc=:
call :new-project !loc!
)
if %1==2 (
call :compile
)
goto :eof

:new-project
mkdir %1
cd %1
if exist .tbp (
  start explorer "%~1"
  goto :eof
)
if not exist .git git init

mkdir lib
git submodules add https://github.com/tumble1999/tbp-core lib/tbp-core
xcopy %tbp-core%\lib\* lib /e
copy %tbp-core%\load-libs.bat %cd%
copy %tbp-core%\.gitmodules %cd%

echo @if not "%%1"=="debug" @echo off>>"%~n1.bat"
echo setlocal enabledelayedexpansion>>"%~n1.bat"
echo call load-libs.bat>>"%~n1.bat"
echo REM %~n1.bat generated by TBP Core>>"%~n1.bat"
echo. >>"%~n1.bat"
echo echo Hello World >>%~n1.bat
echo pause >>%~n1.bat
echo. >>%~n1.bat
echo goto :eof>>%~n1.bat


echo [general]>>.tbp
echo name=%~n1>>.tbp
echo version=0.1>>.tbp

explorer %cd%
cd %tbp-core%
goto:eof

:compile
set /p tbp-folder=drag and drop the project folder here and press enter:
if not exist "%tbp-folder:"=%\.tbp" (
  echo This folder is not a TumbleBatch Project folder.
  goto compile
)

call :list-compile-operations
echo.
set /p op_choice=Choice:
if %op_choice%==1 (
  set operation=C
)
if %op_choice%==2 (
 set operation=D
)
echo.

call :list-compile-types
echo.-choice
set /p type_choice=:
if %type_choice%==1 (
  set type=P
)
if %type_choice%==2 (
 set type=L
)
set /p ins=Would you like an installer[y/n]?
if %ins%==y (
  call projects/compiler.bat %tbp-folder% %operation% %type% installer
) else (
  if %ins%==Y (
    call projects/compiler.bat %tbp-folder% %operation% %type% installer
  ) else (
    call projects/compiler.bat %tbp-folder% %operation% %type%
  )
)
goto :eof

:list-compile-operations
echo 1. Compile
echo 2. Decompile
goto :eof

:list-compile-types
echo 1. Project (.tbp)
echo 2. Library (.tbpl)
goto:eof
