@if not "%1"=="debug" @echo off
setlocal enabledelayedexpansion
set tbp-core=%~dp0
call :display-menu
echo.
set /p choice=Choice:
call :menu %choice%
goto :eof

:display-menu
echo 1. Create Project
echo 2. Compile Project
goto :eof

:menu
cls
if %1==1 (
echo Create Where? - To paste, just right click.
echo (e.g. c:\Users\%USERNAME%\Documents\TumbleBatchProjects\Project1)
set /p loc=:
call :new-project %loc%
)
if %1==2 (
call :compile
)
goto :eof

:new-project
mkdir "%1"
cd %1
if exist .tbp goto :eof
if not exist .git git init

mkdir lib
xcopy %tbp-core%\lib\* lib /e
copy %tbp-core%\load-libs.bat .
copy %tbp-core%\.gitmodules .

echo @if not "%%1"=="debug" @echo off>>%~n1.bat
echo setlocal enabledelayedexpansion>>%~n1.bat
echo call load-libs.bat>>%~n1.bat
echo REM %~n1.bat generated by TBP Core>>%~n1.bat
echo. >>%~n1.bat
echo echo Hello World >>%~n1.bat
echo pause >>%~n1.bat
echo. >>%~n1.bat
echo goto :eof>>%~n1.bat


echo [general]>>.tbp
echo name=%~n1>>.tbp
echo version=0.1>>.tbp

explorer %cd%
cd %tbp-core%
goto:eof

:compile
echo Coming soon
pause
goto :eof
